ALTER TABLE profiles ADD COLUMN IF NOT EXISTS verified BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS ville    TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS site     TEXT;
